-- Sample Technical Questions (MCQ) - Comprehensive Set with 80 Questions

-- Backend / Databases (Easy) - 15 Questions
INSERT INTO technical_questions (question_number, question_text, topic, question_type, difficulty, option_a, option_b, option_c, option_d, correct_answer, explanation, tags) VALUES
(1, 'What does ACID stand for in databases?', 'backend', 'mcq', 'easy', 'Atomicity, Consistency, Isolation, Durability', 'Accuracy, Consistency, Isolation, Durability', 'Atomicity, Correctness, Integrity, Durability', 'Atomicity, Consistency, Integration, Durability', 0, 'ACID: Atomicity, Consistency, Isolation, Durability ensure reliable transactions.', ARRAY['db','transactions']),
(2, 'Which HTTP method is idempotent?', 'backend', 'mcq', 'easy', 'POST', 'PATCH', 'PUT', 'CONNECT', 2, 'PUT is idempotent; multiple identical requests result in the same state.', ARRAY['http','rest']),
(3, 'What status code indicates "Created"?', 'backend', 'mcq', 'easy', '200', '201', '202', '204', 1, '201 Created.', ARRAY['http','rest']),
(4, 'What is the primary purpose of a database index?', 'backend', 'mcq', 'easy', 'To increase storage size', 'To speed up data retrieval', 'To encrypt data', 'To backup data', 1, 'Indexes improve query speed by organizing data.', ARRAY['db','index']),
(5, 'What does REST stand for?', 'backend', 'mcq', 'easy', 'Remote End Service Transfer', 'Representational State Transfer', 'Relational Service Technology', 'Remote Extension Standard Technology', 1, 'REST is an architectural style for distributed systems.', ARRAY['http','api']),
(6, 'Which data structure is LIFO?', 'backend', 'mcq', 'easy', 'Queue', 'Stack', 'Tree', 'Graph', 1, 'Stack follows Last In, First Out principle.', ARRAY['dsa','structures']),
(7, 'What does a primary key ensure?', 'backend', 'mcq', 'easy', 'Automatic backup', 'Unique identification of rows', 'Encryption of data', 'Compression of storage', 1, 'Primary key uniquely identifies each row.', ARRAY['db','constraints']),
(8, 'Which protocol is used for secure HTTP?', 'backend', 'mcq', 'easy', 'HTTP/2', 'HTTPS', 'FTP', 'SMTP', 1, 'HTTPS uses SSL/TLS for encryption.', ARRAY['security','http']),
(9, 'What is a foreign key?', 'backend', 'mcq', 'easy', 'A key that opens databases', 'A reference to a primary key in another table', 'A backup key', 'An encryption key', 1, 'Foreign keys maintain referential integrity.', ARRAY['db','relationships']),
(10, 'What does JSON stand for?', 'backend', 'mcq', 'easy', 'Java System Object Notation', 'JavaScript Object Notation', 'Joint Standard Output Network', 'Java Serialized Object Network', 1, 'JSON is a lightweight data interchange format.', ARRAY['data','formats']),
(11, 'What is the base 2 number system called?', 'backend', 'mcq', 'easy', 'Decimal', 'Binary', 'Octal', 'Hexadecimal', 1, 'Binary is the base 2 number system.', ARRAY['basics','numbers']),
(12, 'Which sorting algorithm is most efficient in worst case?', 'backend', 'mcq', 'easy', 'Bubble Sort', 'Merge Sort', 'Selection Sort', 'Insertion Sort', 1, 'Merge Sort guarantees O(n log n) worst case.', ARRAY['dsa','sorting']),
(13, 'What is caching?', 'backend', 'mcq', 'easy', 'Deleting old data', 'Storing frequently accessed data in fast memory', 'Compressing files', 'Encrypting data', 1, 'Caching improves performance by reducing access time.', ARRAY['performance','memory']),
(14, 'What is API?', 'backend', 'mcq', 'easy', 'A programming language', 'Application Programming Interface for software communication', 'A database backup tool', 'A security protocol', 1, 'APIs enable communication between applications.', ARRAY['api','basics']),
(15, 'What does TCP stand for?', 'backend', 'mcq', 'easy', 'Transfer Control Protocol', 'Transmission Control Protocol', 'Transaction Control Protocol', 'Transport Communication Protocol', 1, 'TCP ensures reliable data transmission.', ARRAY['network','protocols']);

-- Backend / Databases (Medium) - 15 Questions
INSERT INTO technical_questions (question_number, question_text, topic, question_type, difficulty, option_a, option_b, option_c, option_d, correct_answer, explanation, tags) VALUES
(16, 'What is the time complexity of binary search?', 'backend', 'mcq', 'medium', 'O(n)', 'O(log n)', 'O(n log n)', 'O(1)', 1, 'Binary search halves the search space each step.', ARRAY['dsa','search']),
(17, 'Which index type is best for range queries?', 'backend', 'mcq', 'medium', 'Hash index', 'B-Tree index', 'Bitmap index', 'Full-text index', 1, 'B-Tree indexes support ordered scans and ranges.', ARRAY['db','index']),
(18, 'In SQL, what does `LEFT JOIN` return?', 'backend', 'mcq', 'medium', 'Only matching rows', 'All rows from left table and matching rows from right', 'All rows from right table and matching from left', 'Cartesian product', 1, 'LEFT JOIN preserves all rows from the left side.', ARRAY['sql','joins']),
(19, 'What is a primary benefit of using a message queue?', 'backend', 'mcq', 'medium', 'Lower latency than function calls', 'Tight coupling of services', 'Asynchronous decoupling and buffering', 'Guaranteed exactly-once delivery always', 2, 'Queues decouple producers/consumers and buffer load.', ARRAY['architecture','queues']),
(20, 'What is normalization in databases?', 'backend', 'mcq', 'medium', 'Compressing data', 'Organizing tables to reduce redundancy', 'Encrypting sensitive data', 'Backing up data', 1, 'Normalization minimizes data duplication.', ARRAY['db','design']),
(21, 'What does a transaction do?', 'backend', 'mcq', 'medium', 'Performs a single SQL statement', 'Bundles multiple operations into one atomic unit', 'Deletes old records', 'Creates backups', 1, 'Transactions ensure data consistency.', ARRAY['db','transactions']),
(22, 'What is the time complexity of quick sort average case?', 'backend', 'mcq', 'medium', 'O(n)', 'O(n^2)', 'O(n log n)', 'O(log n)', 2, 'Average case quicksort is O(n log n).', ARRAY['dsa','sorting']),
(23, 'What does NoSQL database typically store?', 'backend', 'mcq', 'medium', 'Only text', 'Semi-structured or unstructured data (JSON, documents)', 'Binary files only', 'Images only', 1, 'NoSQL stores flexible, non-relational data.', ARRAY['db','nosql']),
(24, 'What is eventual consistency?', 'backend', 'mcq', 'medium', 'Immediate data consistency everywhere', 'Data becomes consistent after some time', 'Data is never consistent', 'Consistency that requires passwords', 1, 'Eventual consistency is used in distributed systems.', ARRAY['distributed','consistency']),
(25, 'What is load balancing?', 'backend', 'mcq', 'medium', 'Balancing database weight', 'Distributing incoming requests across multiple servers', 'Storing balanced data', 'Encrypting server load', 1, 'Load balancing improves availability and performance.', ARRAY['infrastructure','scaling']),
(26, 'What is connection pooling?', 'backend', 'mcq', 'medium', 'Swimming pool of servers', 'Reusing database connections to reduce overhead', 'Pooling user connections', 'Backup connections', 1, 'Connection pooling improves efficiency.', ARRAY['db','performance']),
(27, 'What does horizontal scaling mean?', 'backend', 'mcq', 'medium', 'Making servers faster', 'Adding more servers to distribute load', 'Making servers wider', 'Removing servers', 1, 'Horizontal scaling adds more machines.', ARRAY['infrastructure','scaling']),
(28, 'What is rate limiting?', 'backend', 'mcq', 'medium', 'Limiting content rating', 'Controlling how many requests a client can make', 'Limiting server speed', 'Limiting database size', 1, 'Rate limiting prevents abuse and overload.', ARRAY['security','api']),
(29, 'What is stateless architecture?', 'backend', 'mcq', 'medium', 'Servers that remember nothing', 'Each request contains all needed information', 'Servers that crash often', 'Servers with no state file', 1, 'Stateless services are easier to scale.', ARRAY['architecture','design']),
(30, 'What does Swagger/OpenAPI provide?', 'backend', 'mcq', 'medium', 'Weather information', 'API documentation and specification', 'Backup solutions', 'Security encryption', 1, 'Swagger/OpenAPI standardizes API documentation.', ARRAY['api','documentation']);

-- Backend / Databases (Hard) - 10 Questions
INSERT INTO technical_questions (question_number, question_text, topic, question_type, difficulty, option_a, option_b, option_c, option_d, correct_answer, explanation, tags) VALUES
(31, 'What is the main advantage of CQRS?', 'backend', 'mcq', 'hard', 'Simpler codebase', 'Single datastore', 'Separates read/write models for scaling and clarity', 'Removes need for caching', 2, 'CQRS decouples commands from queries for scale/performance.', ARRAY['architecture','cqrs']),
(32, 'Which isolation level can still suffer from phantom reads?', 'backend', 'mcq', 'hard', 'Read Uncommitted', 'Read Committed', 'Repeatable Read (non-serializable)', 'Serializable', 2, 'Repeatable Read may allow phantoms unless serializable.', ARRAY['db','transactions']),
(33, 'What is a common downside of two-phase commit?', 'backend', 'mcq', 'hard', 'No coordination needed', 'Higher availability', 'Coordinator is a single point of failure and slow', 'Better latency', 2, '2PC adds latency and a coordinator SPOF.', ARRAY['distributed','transactions']),
(34, 'What is the CAP theorem?', 'backend', 'mcq', 'hard', 'Three phases of deployment', 'Consistency, Availability, Partition tolerance - pick 2 of 3', 'Cache, API, Protocol', 'Computer, Algorithm, Processor', 1, 'CAP theorem shows trade-offs in distributed systems.', ARRAY['distributed','theory']),
(35, 'What problem does event sourcing solve?', 'backend', 'mcq', 'hard', 'Email delivery', 'Maintaining complete audit trail and rebuilding state', 'Speed of requests', 'User authentication', 1, 'Event sourcing stores all state changes.', ARRAY['architecture','patterns']),
(36, 'What is sharding?', 'backend', 'mcq', 'hard', 'Sharing server resources', 'Partitioning data across multiple servers by key', 'Backing up shards of data', 'Securing data shards', 1, 'Sharding enables horizontal scaling of databases.', ARRAY['db','scaling']),
(37, 'What is a deadlock in databases?', 'backend', 'mcq', 'hard', 'A type of backup', 'Circular wait on resources preventing progress', 'Locked database', 'A security feature', 1, 'Deadlocks prevent transaction progress.', ARRAY['db','concurrency']),
(38, 'What does idempotency mean?', 'backend', 'mcq', 'hard', 'Many operations', 'Multiple identical requests produce the same result', 'Identical systems', 'Ideal methodology', 1, 'Idempotent operations are safe to repeat.', ARRAY['api','design']),
(39, 'What is eventual consistency vs strong consistency?', 'backend', 'mcq', 'hard', 'Eventual is newer', 'Eventual: data eventually consistent; Strong: immediately consistent', 'They mean the same thing', 'Eventual is stronger', 1, 'Trade-off between availability and consistency.', ARRAY['distributed','consistency']),
(40, 'What does circuit breaker pattern do?', 'backend', 'mcq', 'hard', 'Breaks circuits in code', 'Prevents cascading failures by failing fast', 'Increases load', 'Stores data', 1, 'Circuit breaker stops requests when service is down.', ARRAY['resilience','patterns']);

-- Frontend / Web (Easy) - 15 Questions
INSERT INTO technical_questions (question_number, question_text, topic, question_type, difficulty, option_a, option_b, option_c, option_d, correct_answer, explanation, tags) VALUES
(41, 'What does CSS Flexbox primarily help with?', 'frontend', 'mcq', 'easy', 'Grid-based layouts only', 'One-dimensional layouts (row/column)', 'Two-dimensional layouts', 'Animation sequencing', 1, 'Flexbox is for one-dimensional flow.', ARRAY['css','layout']),
(42, 'Which HTML element is semantic for navigation?', 'frontend', 'mcq', 'easy', '<section>', '<aside>', '<nav>', '<article>', 2, '<nav> denotes navigation links.', ARRAY['html','semantic']),
(43, 'What does `===` do in JavaScript?', 'frontend', 'mcq', 'easy', 'Assignment', 'Loose equality with coercion', 'Strict equality without coercion', 'Bitwise AND', 2, '=== compares value and type.', ARRAY['js','basics']),
(44, 'What is DOM?', 'frontend', 'mcq', 'easy', 'Document Object Model - tree of HTML elements', 'A design pattern', 'A database', 'A styling language', 0, 'DOM represents the page structure.', ARRAY['dom','html']),
(45, 'What does CSS stand for?', 'frontend', 'mcq', 'easy', 'Computer Style Sheets', 'Cascading Style Sheets', 'Code Structure Standard', 'Cascading Server Sheets', 1, 'CSS styles HTML elements.', ARRAY['css','basics']),
(46, 'What is the purpose of `<meta charset>`?', 'frontend', 'mcq', 'easy', 'To set the page title', 'To define character encoding (UTF-8)', 'To link stylesheets', 'To create navigation', 1, 'Charset meta tag ensures text is properly decoded.', ARRAY['html','encoding']),
(47, 'What is a JavaScript callback?', 'frontend', 'mcq', 'easy', 'A return value', 'A function passed to another function to be executed later', 'A loop construct', 'A variable type', 1, 'Callbacks enable asynchronous operations.', ARRAY['js','async']),
(48, 'What does `console.log()` do?', 'frontend', 'mcq', 'easy', 'Ends the program', 'Prints output to browser console', 'Logs in to a server', 'Creates a button', 1, 'console.log() is used for debugging.', ARRAY['js','debugging']),
(49, 'What is a CSS class selector?', 'frontend', 'mcq', 'easy', 'A class definition', 'Using `.className` to select HTML elements', 'A type selector', 'An ID selector', 1, 'Classes start with dot (.) in CSS.', ARRAY['css','selectors']),
(50, 'What is the purpose of `alt` attribute in images?', 'frontend', 'mcq', 'easy', 'Alternative image file', 'Alternative text for accessibility', 'Alignment tool', 'Alternate URL', 1, 'Alt text describes image for screen readers.', ARRAY['html','accessibility']),
(51, 'What does responsive design mean?', 'frontend', 'mcq', 'easy', 'Quick to respond to user input', 'Adapting layout to different screen sizes', 'Making things move fast', 'Quick animations', 1, 'Responsive design works on all devices.', ARRAY['css','responsive']),
(52, 'What is a media query?', 'frontend', 'mcq', 'easy', 'A query to media servers', 'CSS condition to apply styles based on device', 'A video player', 'A search function', 1, 'Media queries enable responsive design.', ARRAY['css','responsive']),
(53, 'What is the difference between `var`, `let`, and `const`?', 'frontend', 'mcq', 'easy', 'They are the same', '`let` and `const` are block-scoped; `var` is function-scoped', 'They all do the same thing', 'No difference', 1, '`let` and `const` have block scope; `var` has function scope.', ARRAY['js','variables']),
(54, 'What does `typeof` operator return?', 'frontend', 'mcq', 'easy', 'The class of an object', 'A string representing the data type', 'The variable type', 'Nothing', 1, 'typeof returns a string of the data type.', ARRAY['js','operators']),
(55, 'What is an HTML form?', 'frontend', 'mcq', 'easy', 'A document format', 'Interactive controls to collect user input', 'A shape', 'A template', 1, 'Forms collect data from users.', ARRAY['html','forms']);

-- Frontend / Web (Medium) - 15 Questions
INSERT INTO technical_questions (question_number, question_text, topic, question_type, difficulty, option_a, option_b, option_c, option_d, correct_answer, explanation, tags) VALUES
(56, 'Which hook runs after every render in React?', 'frontend', 'mcq', 'medium', 'useMemo', 'useEffect', 'useCallback', 'useRef', 1, 'useEffect runs after paint by default.', ARRAY['react','hooks']),
(57, 'What does CORS protect against?', 'frontend', 'mcq', 'medium', 'SQL injection', 'Cross-site request forgery', 'Unauthorized cross-origin requests', 'XSS payload execution', 2, 'CORS controls cross-origin resource access.', ARRAY['security','web']),
(58, 'What is tree shaking?', 'frontend', 'mcq', 'medium', 'Minifying CSS', 'Removing unused JS exports at build time', 'Lazy loading images', 'Server-side rendering', 1, 'Tree shaking drops unused exports in bundlers.', ARRAY['bundling','performance']),
(59, 'What is the purpose of `useEffect` cleanup?', 'frontend', 'mcq', 'medium', 'Clean the screen', 'Remove listeners/subscriptions when component unmounts', 'Clear cache', 'Reset state', 1, 'Cleanup prevents memory leaks.', ARRAY['react','hooks']),
(60, 'What does `useMemo` do?', 'frontend', 'mcq', 'medium', 'Memoizes functions', 'Memoizes expensive computations', 'Stores data permanently', 'Clears memory', 1, 'useMemo caches computation results.', ARRAY['react','performance']),
(61, 'What is prop drilling?', 'frontend', 'mcq', 'medium', 'Creating drill tools', 'Passing props through multiple layers', 'Adding props to DOM', 'Removing properties', 1, 'Prop drilling passes data deeply through components.', ARRAY['react','state']),
(62, 'What is the difference between `==` and `===`?', 'frontend', 'mcq', 'medium', 'No difference', '== coerces types; === strict equality', 'They do the same', '=== is faster', 1, '=== is preferred for avoiding type coercion bugs.', ARRAY['js','operators']),
(63, 'What are async/await?', 'frontend', 'mcq', 'medium', 'Waiting for memory', 'Syntax for handling promises more readably', 'A type of loop', 'A data structure', 1, 'async/await simplifies promise handling.', ARRAY['js','async']),
(64, 'What is a Promise in JavaScript?', 'frontend', 'mcq', 'medium', 'A commitment to do something', 'Object representing eventual completion/failure of async op', 'A function declaration', 'A variable', 1, 'Promises handle asynchronous operations.', ARRAY['js','async']),
(65, 'What does `.map()` do in JavaScript?', 'frontend', 'mcq', 'medium', 'Creates a geographical map', 'Transforms each element in array and returns new array', 'Finds elements', 'Sorts arrays', 1, '.map() applies function to each element.', ARRAY['js','arrays']),
(66, 'What is event delegation?', 'frontend', 'mcq', 'medium', 'Creating event committees', 'Using a parent listener for multiple child elements', 'Removing event listeners', 'Adding multiple listeners', 1, 'Event delegation improves performance.', ARRAY['js','events']),
(67, 'What is lazy loading?', 'frontend', 'mcq', 'medium', 'Loading things slowly', 'Loading resources only when needed', 'Delaying the whole page', 'Fast loading', 1, 'Lazy loading improves initial page load time.', ARRAY['performance','optimization']),
(68, 'What does `display: none` do in CSS?', 'frontend', 'mcq', 'medium', 'Makes text invisible', 'Completely removes element from layout', 'Hides element but keeps space', 'Changes opacity', 1, 'display: none removes element from layout.', ARRAY['css','display']),
(69, 'What is `z-index` in CSS?', 'frontend', 'mcq', 'medium', 'Horizontal positioning', 'Controls stacking order (depth) of elements', 'Vertical positioning', 'Animation speed', 1, 'z-index determines layer ordering.', ARRAY['css','positioning']),
(70, 'What is the virtual DOM in React?', 'frontend', 'mcq', 'medium', 'A fake website', 'In-memory representation for efficient diffing', 'A separate server', 'A backup DOM', 1, 'Virtual DOM improves React performance.', ARRAY['react','performance']);

-- Frontend / Web (Hard) - 10 Questions
INSERT INTO technical_questions (question_number, question_text, topic, question_type, difficulty, option_a, option_b, option_c, option_d, correct_answer, explanation, tags) VALUES
(71, 'What problem does React Concurrent Mode address?', 'frontend', 'mcq', 'hard', 'Improving bundle size', 'Coordinating async rendering for responsiveness', 'Adding server-side rendering', 'Managing state', 1, 'Concurrent rendering lets React stay responsive under load.', ARRAY['react','performance']),
(72, 'Which security header mitigates clickjacking?', 'frontend', 'mcq', 'hard', 'Content-Security-Policy', 'X-Frame-Options', 'Strict-Transport-Security', 'X-Content-Type-Options', 1, 'X-Frame-Options blocks framing attacks.', ARRAY['security','headers']),
(73, 'What does a Service Worker primarily enable?', 'frontend', 'mcq', 'hard', 'DOM manipulation', 'Server rendering', 'Offline caching and network proxying', 'Improved SEO', 2, 'Service Workers intercept requests and cache.', ARRAY['pwa','caching']),
(74, 'What is closure in JavaScript?', 'frontend', 'mcq', 'hard', 'Ending a program', 'Function with access to variables from outer scope', 'A closed loop', 'A data type', 1, 'Closures enable data privacy and callbacks.', ARRAY['js','advanced']),
(75, 'What is hoisting in JavaScript?', 'frontend', 'mcq', 'hard', 'Lifting things up', 'Variables/functions moved to top of scope before execution', 'Loading order', 'Function nesting', 1, 'Hoisting can lead to undefined variable bugs.', ARRAY['js','advanced']),
(76, 'What does REST architectural style emphasize?', 'frontend', 'mcq', 'hard', 'Procedure calls', 'Resources, HTTP methods, statelessness', 'Remote execution', 'Tight coupling', 1, 'REST focuses on resources and HTTP methods.', ARRAY['api','architecture']),
(77, 'What is memoization in React?', 'frontend', 'mcq', 'hard', 'Remembering things', 'Caching component results to prevent re-renders', 'Storing memory', 'Clearing cache', 1, 'React.memo memoizes functional components.', ARRAY['react','optimization']),
(78, 'What is Web Storage (localStorage/sessionStorage)?', 'frontend', 'mcq', 'hard', 'A cloud service', 'Client-side storage persisting across sessions', 'Server-side storage', 'A database', 1, 'Web Storage stores data on the client.', ARRAY['storage','web']),
(79, 'What does Content Security Policy (CSP) prevent?', 'frontend', 'mcq', 'hard', 'All scripts', 'XSS attacks by restricting resource origins', 'CSS styling', 'Form submissions', 1, 'CSP mitigates injection attacks.', ARRAY['security','headers']),
(80, 'What is reconciliation in React?', 'frontend', 'mcq', 'hard', 'Fixing code', 'Process of updating DOM to match new component state', 'Merging files', 'Comparing objects', 1, 'Reconciliation makes React efficient.', ARRAY['react','internals']);
